#!/bin/bash
echo $(pwd)
docker container run \
-it \
--rm \
--name=spiking-model-control-connector \
-p 5000:5000 \
-p 5003:3000 \
-v "$(pwd)":/app \
-v "$(pwd)"/../spiking-model-configuration/configuration/:/configuration \
louisross/spiking-model-control-connector:1.1 \
bash
